// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'stream_chat_model.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'stream_chat_model.g.dart';

@freezed
class StreamChatModel with _$StreamChatModel {
  const factory StreamChatModel({
    required String? id,
    required String message,
    required String from,
    required DateTime createdAt,
    required String thread,
    required String? fromName,
    required String? fromImageUrl,
  }) = _StreamChatModel;

  factory StreamChatModel.fromJson(Map<String, Object?> json) =>
      _$StreamChatModelFromJson(json);
}
