// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'stream_model.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'stream_model.g.dart';

@freezed
class StreamModel with _$StreamModel {
  const factory StreamModel({
    required String title,
    required String hostName,
    required DateTime startAt,
    required DateTime endAt,
    required String channelId,
    required String channelToken,
    required String hostId,
    required String thumbnailUrl,
  }) = _StreamModel;

  factory StreamModel.fromJson(Map<String, Object?> json) =>
      _$StreamModelFromJson(json);
}
