// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'random_video_model.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'random_video_model.g.dart';

@freezed
class RandomVideoModel with _$RandomVideoModel {
  const factory RandomVideoModel({
    required String? channel,
    required String key,
    required bool repeat,
    required bool skip,
    required String token,
  }) = _RandomVideoModel;

  factory RandomVideoModel.fromJson(Map<String, Object?> json) =>
      _$RandomVideoModelFromJson(json);
}
