// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'messages_model.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'messages_model.g.dart';

@freezed
class MessagesModel with _$MessagesModel {
  const factory MessagesModel({
    required String? id,
    required String message,
    required String from,
    required DateTime createdAt,
    required String thread,
    required String? fromName,
    required String? fromImageUrl,
     bool? seen,
  }) = _MessagesModel;

  factory MessagesModel.fromJson(Map<String, Object?> json) =>
      _$MessagesModelFromJson(json);
}
